# Generated by Django 5.0.4 on 2024-04-10 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['name', 'price', 'page_count', 'author_name'], 'verbose_name': 'book', 'verbose_name_plural': 'books'},
        ),
        migrations.AlterField(
            model_name='book',
            name='author_name',
            field=models.CharField(max_length=100, verbose_name='author name'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(max_length=100, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='book',
            name='page_count',
            field=models.IntegerField(verbose_name='page count'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.IntegerField(verbose_name='Price'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['name'], name='name_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['price'], name='price_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['page_count'], name='page_count_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['author_name'], name='author_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.UniqueConstraint(fields=('name', 'author_name'), name='unique_book'),
        ),
    ]
