# Generated by Django 5.0.4 on 2024-04-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_alter_book_options_remove_book_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='categories',
            field=models.ManyToManyField(related_name='books', to='market.category', verbose_name='categories'),
        ),
    ]
