# Generated by Django 5.0.4 on 2024-04-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_alter_book_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.CharField(choices=[('HC', 'Hard cover'), ('SC', 'Soft cover'), ('SPC', 'Special cover')], default=None, max_length=3, verbose_name='cover type'),
        ),
    ]
